### PR TITLE
Don't reset modified flag on REPL input

### PR DESCRIPTION
**Pull request by mfussenegger**
Might solve https://github.com/mfussenegger/nvim-dap/issues/119

### CODE REVIEW

**Comment by theHamsta** [comment]
I personally find the `did not save "[dap-repl]"` messages much more annoying than not being able to use `<bs>`. But that's just a personal opinion. We found no other way to tell Vim that this is not a normal file that needs to be saved the last time, didn't we?

**Comment by mfussenegger** [comment]
> We found no other way to tell Vim that this is not a normal file that needs to be saved the last time, didn't we

I don't think so,  I'll have another look and otherwise file something in neovim core

**Comment by mfussenegger** [comment]
https://github.com/vim/vim/commit/4551c0a9fcdbdef52836d4852686d54b5e47fdaf makes it sound as the behavior was somewhat intentional?

Maybe an option would be do the `api.nvim_buf_set_option(buf, 'modified', false)` call less often? E.g. on `WinLeave` or something like that.

**Comment by theHamsta** [comment]
That's why we have Neovim. To not be dependent on someone who wants some weird behavior and ends up hard-coding it into C. Pretty strange though that this is not configurable. Well it makes sense if you don't use `set bufhidden=hide`. But most people do.

With the events we did not hit every change of the buffer.

**Comment by theHamsta** [comment]
In vlime (a Lisp plugin with REPL), we also tried many combinations of making the buffer non-editable and make it automatically non-modified. Main-problem was that Lisp can only print parts of a line but you're not supposed to modify it. Just text you wrote. But in the end we found no satisfying solution and you still cannot enter text in the REPL. I have the feeling that this can probably only be tackled in vim itself.

**Comment by theHamsta** [comment]
Another bug is that you get only text output in the REPL when you have been at least once in input mode. Otherwise, no output will appear in the prompt buffer.

**Comment by mfussenegger** [comment]
https://github.com/mfussenegger/nvim-dap/pull/123 is probably the better option to workaround the backspace issue. Closing this here.

**Pull request closed without merging**
