### PR TITLE
Handle paths relative to custom path in utils.pick_file

### PR DESCRIPTION
**Pull request by mfussenegger**
Should fix https://github.com/mfussenegger/nvim-dap/issues/1220

### CODE REVIEW

**Comment by cryptomilk** [comment]
Unfortunatly this doesn't fix it :-(

**Comment by cryptomilk** [comment]
Oh. the directory is wrong:

```
stat on default/source3/lib/netapi/examples/localgroup/localgroup_getmembers                                                                                                        
no stat
```

I pass /home/asn/workspace/prj/oss/samba/bin too it. So it thinks this is the current working directory, but the cwd is `/home/asn/workspace/prj/oss/samba`

It should be `bin/default/source3/lib/netapi/examples/localgroup/localgroup_getmembers `

**Comment by mfussenegger** [comment]
Right, I should've used the joined path for the filter too :)

Can you check the last fixup?

**Comment by cryptomilk** [comment]
This works! Yay :-)

**Pull request merged**
