### PR TITLE
fix split repl lines issue

### PR DESCRIPTION
**Pull request by y1rn**
image

In this debug step by step case expect:
(
initial
1 2
 true
 0
 apple
)

### CODE REVIEW

**Comment by mfussenegger** [comment]
I assume this is partially related to the `require('dap.repl').append(chunk)` from https://github.com/mfussenegger/nvim-dap/issues/232 ?

I think instead of trimming the last newline within the repl append code, this should rather be done on the call-site already.

You could wrap the chunk in an `vim.trim()` call.

**Comment by y1rn** [comment]
i have been debug rust file, still has the same issue.

**Comment by mfussenegger** [comment]
Ah, I see.

I've merged the change with https://github.com/mfussenegger/nvim-dap/commit/55f2737dcfb2f0d846623ae3996cf141bb692fab

**Comment by y1rn** [comment]
i work with vim.trim() well, i'v amend my fork https://github.com/y1rn/nvim-dap/commit/d2bf364952eea328fcea33671e6654e59c736c26

**Pull request closed without merging**
