### PR TITLE
feat(widgets): quit floats with q

### PR DESCRIPTION
**Pull request by igorlfs**
Addresses a suggestion I made in https://github.com/mfussenegger/nvim-dap/issues/1194#issuecomment-2140501146.

### CODE REVIEW

**Review by mfussenegger — COMMENTED** [review]
I'm not sure about this - if every plugin ends up mapping `q` then this should probably just be a default in neovim core instead for floating windows.

If it isn't a good default for all plugins, then I wonder why it should be done here. Having it work in one plugin but not another is odd.

If you do want to have it, you can register a FileType autocmd on `dap-float`, or you could even do a `WinEnter` and check if it's a floating window to set it generally.

**Comment by igorlfs** [comment]
>  if every plugin ends up mapping `q` then this should probably just be a default in neovim core instead for floating windows.

That sounds like a better approach, but I'm unsure if other maintainers would be willing to accept such change (though it's common within core, e.g., for diagnostics and hover). If you're okay with this, I'll file an issue in core. 

> If it isn't a good default for all plugins, then I wonder why it should be done here. Having it work in one plugin but not another is odd.

IMO it's a good default for all plugins (if not, the vast majority). At least, most of the plugin I use, anyway.

> If you do want to have it, you can register a FileType autocmd on `dap-float`

That's what I currently have, but your second idea sounds better, thanks!

**Comment by mfussenegger** [comment]
> If you're okay with this, I'll file an issue in core.

yes please.
I'm closing this here for now

**Comment by igorlfs** [comment]
For reference, here's the issue on core: https://github.com/neovim/neovim/issues/31706

**Pull request closed without merging**
